// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPGFJqKu2gXVfSRE0RHWdlE62d0aF-ftM',
    appId: '1:1001970077172:web:4dee36d5d96b8bd954fda1',
    messagingSenderId: '1001970077172',
    projectId: 'otdaapp-258f8',
    authDomain: 'otdaapp-258f8.firebaseapp.com',
    storageBucket: 'otdaapp-258f8.appspot.com',
    measurementId: 'G-MXSN5YXVSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVXWj6GmRDDFb8JOm170UuFAn2uwvEQc',
    appId: '1:1001970077172:android:e4bdadfdf6d3a6f454fda1',
    messagingSenderId: '1001970077172',
    projectId: 'otdaapp-258f8',
    storageBucket: 'otdaapp-258f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrdWpFd35xWfvdX9w5QeeP0bjSpPEJNC8',
    appId: '1:1001970077172:ios:49937e5eb828245854fda1',
    messagingSenderId: '1001970077172',
    projectId: 'otdaapp-258f8',
    storageBucket: 'otdaapp-258f8.appspot.com',
    iosClientId: '1001970077172-0l6s6prg8e5ld39omd0sn3gk3svjvug1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appV2',
  );
}
